[package]
name = "anime_dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
tokio = { version = "1.33.0", features = ["full"] }
futures = "0.3.29"
thirtyfour = "*"
zip-extract = "*"
sevenz-rust = "0.5.4"
indicatif = "0.17.0"
