[package]
name = "anime_dl"
version = "0.6.0"
edition = "2021"
homepage = "https://github.com/PsykoDev/neko_sama_downloader"
repository = "https://github.com/PsykoDev/neko_sama_downloader"
readme = "README.md"
authors = ["PsykoDev"]
description = "neko-sama.fr downloader by episode or by saison"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
opt-level = "z"
strip = true
codegen-units = 1

[profile.release.build-override]
opt-level = "z"
strip = true
codegen-units = 1

[dependencies]
indicatif = "0.17.7"
reqwest = "0.11.23"
clap = { version = "4.4.14", features = ["derive"] }
crossbeam-channel = "0.5.11"
serde_derive = "1.0.195"
crossbeam = "0.8.4"
regex = "1.10.2"
quick-xml = "0.31.0"
tokio = "1.35.1"
thirtyfour = "0.32.0-rc.9"
ctrlc = "3.4.2"
strsim = "0.11.0"
serde_json = "1.0.111"
serde = "1.0.195"
requestty = "0.5.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"