[package]
name = "neko_dl"
version = "0.13.1"
edition = "2021"
homepage = "https://github.com/CatAnnaDev/neko_sama_downloader"
repository = "https://github.com/CatAnnaDev/neko_sama_downloader"
readme = "README.md"
authors = ["CatAnnaDev"]
description = "neko-sama.fr downloader by episode or by saison"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
opt-level = "z"
strip = true
codegen-units = 1

[profile.release.build-override]
opt-level = "z"
strip = true
codegen-units = 1

[dependencies]
indicatif = "0.17.8"
reqwest = "0.12.5"
clap = { version = "4.5.7", features = ["derive"] }
crossbeam-channel = "0.5.13"
serde_derive = "1.0.203"
crossbeam = "0.8.4"
regex = "1.10.5"
quick-xml = "0.33.0"
tokio = "1.38.0"
thirtyfour = "0.33.0-alpha.2"
ctrlc = "3.4.4"
strsim = "0.11.1"
serde_json = "1.0.117"
serde = "1.0.203"
requestty = "0.5.0"
m3u8-rs = "6.0.0"
nom = "8.0.0-alpha2"
http = "1.1.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"