[package]
name = "anime_dl"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/PsykoDev/neko_sama_downloader"
repository = "https://github.com/PsykoDev/neko_sama_downloader"
readme = "README.md"
authors = ["PsykoDev"]
description = "neko-sama.fr downloader by episode or by saison"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
opt-level = "z"
strip = true
codegen-units = 1

[profile.release.build-override]
opt-level = "z"
strip = true
codegen-units = 1

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
tokio = { version = "1.33.0", features = ["full"] }
futures = "0.3.29"
thirtyfour = "*"
indicatif = "0.17.0"
quick-xml = { version = "0.31.0", features = [] }
regex = "1.10.2"
crossbeam = "0.8.2"
serde_derive = { version = "1.0.193", features = [] }
serde = "1.0.193"
serde_json = "1.0.108"
strsim = "0.10.0"
clap = { version = "4.4.12", features = ["derive"] }
